### ISSUE TITLE
practica de operaciones básicas 

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-saul19bautista#1]
[PRACTICAS DE OPERACIONES BASICA SAUL LOPEZ BAUTISTA.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-saul19bautista/files/7150491/PRACTICAS.DE.OPERACIONES.BASICA.SAUL.LOPEZ.BAUTISTA.pdf)

**Comment by josealfredo79** [comment]
aqui debe ir la calificación de acuerdo a evaluación

**Comment by irving1613** [comment]
Buen trabajo, ejercicios bien resueltos
**Calificacion: 20**

**Comment by josealfredo79** [comment]
Bien hecho y revisado
